### PR TITLE
add width and height propertty picker

### PR DESCRIPTION
**Pull request by MGarcia93**

### CODE REVIEW

**Comment by toolcool-org** [comment]
Hello, thanks for the input. I'm very excited to see the first pull request for this project. I would like to check if I understand correctly what this code does. Is it intended to resize the button (width and height) using predefined names like "sm", "lg", "2xl", etc.?

**Comment by MGarcia93** [comment]
yes, change width and height with absolute size(16px,15rem,etc) or using predefined names(sm,xl,etc)

**Comment by toolcool-org** [comment]
All is great, the only changes I think should be done are:

- change **width** / **height** attributes to **button-width** and **button-height** instead, because in the future I'm planning to add possibility to change popup width too with popup-width and popup-height attributes.
- and the same change with css variable: change **--tool-cool-width-picker-span** to **--tool-cool-color-picker-btn-width**, and **--tool-cool-height-picker-span** to **--tool-cool-color-picker-btn-height**

Sounds reasonable?

**Comment by MGarcia93** [comment]
seem right.
add commint in pr, changing the display of elements to flexbox so that relative sizes can also be used and make it more attached to the page

**Comment by toolcool-org** [comment]
Awesome. I'll review and approve the PR tomorrow as it's getting late here. Good night

**Pull request merged**
